### ISSUE TITLE
I'm wondering whether the optimizer can be Adam

### ISSUE THREAD

**Issue by 1069066484** [wogong/pytorch-dann#7]
I've seen several implementations of GRL, where SGD optimizer is utilized. Is it must be SGD? Can the optimizer be Adam? I tried Adam in my project, but it seems not to work.

**Comment by Data-Designer** [comment]
> I've seen several implementations of GRL, where SGD optimizer is utilized. Is it must be SGD? Can the optimizer be Adam? I tried Adam in my project, but it seems not to work.
Adam有时候应该也行吧
